apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-env
data:
  MAIN_ROUTE: "http://localhost:"
  PORT: "7007"
  JWT_ACCESS_SECRETKEY: "USER_ACCESS_SECRET_KEY"
  JWT_REFRESH_SECRETKEY: "USER_REFRESH_SECRET_KEY"
  ADMIN_JWT_ACCESS_SECRETKEY: "ADMIN_ACCESS_SECRET_KEY"
  ADMIN_JWT_REFRESH_SECRETKEY: "ADMIN_REFRESH_SECRET_KEY"
  FRONTEND_PORT: "5173"
  MONGO_URI: "mongodb+srv://afsalrahmanm25:hKg8ZVDO4S18BNUB@cluster0.zmpcm.mongodb.net/Admin_LostLink?retryWrites=true&w=majority&appName=Cluster0"
  AMQP_URL: "amqp://rabbitmq:5672"
  ADMIN_QUEUE: "ADMIN"
  AUTH_QUEUE: "AUTH"
  USER_QUEUE: "USER"
