apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: afsalm/lostlink-chat-service:v9
          ports:
            - containerPort: 7005
          envFrom:
            - configMapRef:
                name: chat-service-env

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - port: 7005
      targetPort: 7005
  type: ClusterIP
